[package]
name = "valser"
version = "0.1.1"
edition = "2021"
license = "CC0-1.0"
description = "Structure schema library for Rust"

[dependencies]
either = { version = "1.13.0", default-features = false }

[features]
alloc=[]
